name: Check for new vllm release

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  check-release:
    runs-on: ubuntu-latest

    outputs:
      latest-release: ${{ steps.latest.outputs.LATEST_RELEASE }}
      current-release: ${{ steps.current.outputs.CURRENT_RELEASE }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl jq

      - name: Get latest vllm release
        id: latest
        run: |
          VLLM_LATEST=$(curl -s https://pypi.org/pypi/vllm/json | jq -r '.info.version')
          echo "LATEST_RELEASE=$VLLM_LATEST" >> $GITHUB_OUTPUT
          echo "Latest vllm version: "$VLLM_LATEST

      - name: Get current vllm release for Power
        id: current
        run: |
          VLLM_CURRENT=$(curl -s https://api.github.com/repos/DahlitzFlorian/vllm-ppc64le/releases/latest | grep tag_name | cut -d '"' -f4)
          echo "CURRENT_RELEASE=$VLLM_CURRENT" >> $GITHUB_OUTPUT
          echo "Current vllm version on Power: "$VLLM_CURRENT

  build-new-release:
    needs: [check-release]
    if: needs.check-release.outputs.latest-release != needs.check-release.outputs.current-release
    uses: ./.github/workflows/build_vllm.yaml
    with:
      release: ${{ needs.check-release.outputs.latest-release }}
